name: 'Semverify'
description: 'checks if each semantic version exists exactly once'
inputs:
  token:
    description: token to create the octocat client
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
runs:
  using: 'node12'
  main: 'dist/index.js'