on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: adlerhurst/semverify@init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          who-to-greet: 'Mona the Octocat'